---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

collections:
- name: "ansible.posix"
- name: "community.general"
- name: "adhawkins.borgbase"

roles:
- src: "jnv.debian-backports"
