---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: "Install Borgbackup from backports"
  ansible.builtin.apt:
    name: "{{ borgbackup_package }}"
    default_release: "{{ ansible_distribution_release }}-backports"
    # noqa: args[module]
    state: "{{ borgbackup_package_state }}"
  when:
  - "__borgbackup_apt_backport is defined"
  - "__borgbackup_apt_backport"

- name: "Install Borgbackup"
  ansible.builtin.package:
    name: "{{ borgbackup_package }}"
    state: "{{ borgbackup_package_state }}"
  when:
  - "__borgbackup_apt_backport is not defined or not __borgbackup_apt_backport"

- name: "Install Borgmatic"
  ansible.builtin.pip:
    name:
    - "borgmatic"
    executable: "pip3"
    state: "present"

- name: "Install the silencer script"
  ansible.builtin.copy:
    src: "silence-unless-failed"
    dest: "/usr/local/bin/silence-unless-failed"
    mode: "u=rwx,go=rx"
    owner: "root"
    group: "root"
