---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: 'Converge'
  hosts: 'all'
  become: true

  vars:
    borgbase_repository_fullpath: "test-repo:/./repo"

  pre_tasks:
  - name: 'Make sure the package cache is up to date'
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 600
    when: 'ansible_os_family == "Debian"'

  - name: 'Make sure we have required tools'
    ansible.builtin.package:
      name:
      - 'pwgen'
      - 'cron'
      state: 'present'
    when:
    - "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"

  - name: 'Make sure we have required tools'
    ansible.builtin.package:
      name:
      - 'pwgen'
      - 'cronie'
      state: 'present'
    when:
    - "ansible_os_family == 'RedHat' or ansible_os_family == 'Suse'"
    - "ansible_distribution != 'Amazon'"
    - "ansible_distribution != 'RedHat'"

  roles:
  - role: "jnv.debian-backports"
    when:
    - "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"
  - role: 'mireiawen.borgbase'
    when:
    - "ansible_distribution != 'Amazon'"
    - "ansible_distribution != 'RedHat'"
